spring.application.name=VD_JWT

server.port=8005

spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=BT_JWT;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YOUR_SQL_SERVER_PASSWORD 
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

security.jwt.secret-key=YOUR_SETCRET_KEY
security.jwt.expiration-time=3600000
security.cors.allowed-origins=http://localhost:8005